### ISSUE TITLE
1.27.0 release

### ISSUE THREAD

**Issue by dgsqrs** [TerrenceHenry/Raspberry-Pi-Ubuntu-Cardano-Node-Binaries#1]
Hi there.
Thanks for the 1.26 binaries.

Have you any plan about the 1.27 ?

**Comment by TerrenceHenry** [comment]
Hi,

Yes, I've built it, but still testing.
I'll release it as soon as it looks ok.

Pi seems to be taking longer than normal to get started.

**Comment by dgsqrs** [comment]
Great, let me know if I can help

**Comment by jacky4566** [comment]
+1, also digging around for a 1.27 binary.

**Comment by TerrenceHenry** [comment]
Just released. V1.27.0
